name: Deploy to VPS

on:
  push:
    branches: [ main ]  # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install PM2
        run: npm install pm2 -g
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /caminho/para/seu/projeto
            git pull origin main
            npm install
            pm2 reload ecosystem.config.js 